# Generated by Django 4.2.16 on 2024-11-09 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('min_stock', models.IntegerField()),
                ('tax', models.IntegerField(null=True)),
                ('tax_type', models.IntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('product_image', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='api.user')),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
