# Generated by Django 4.2.16 on 2025-03-02 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_due_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='api.OrderDetail', to='api.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat',
            field=models.FloatField(),
        ),
    ]
