# Generated by Django 4.2.16 on 2025-03-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_order_due_date_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.IntegerField(default=0),
        ),
    ]
