# Generated by Django 4.2.16 on 2025-03-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_due'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='OrderItem',
        ),
    ]
