# Generated by Django 4.2.16 on 2025-03-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_orderdetail_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
