# Generated by Django 4.2.16 on 2025-03-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
