# Generated by Django 4.2.16 on 2025-02-09 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_location_order_orderdetail_quotation_shipment_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='from_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='to_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(through='api.WarehouseProduct', to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('incoming', 'Incoming (Supplier → Warehouse)'), ('outgoing', 'Outgoing (Warehouse → Customer)')], default='incoming', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipped_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipped_to',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ManyToManyField(through='api.CustomerUser', to='api.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin User'), ('staff', 'Staff User'), ('super_admin', 'Super Admin'), ('customer', 'Customer User')], default='customer', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='produtcs',
            field=models.ManyToManyField(through='api.WarehouseProduct', to='api.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sale_orders', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('sale order', 'Sale Order'), ('purchase', 'Purchase Order'), ('transfer order', 'Transfer Order')]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.warehouse')),
            ],
        ),
    ]
