# Generated by Django 4.2.16 on 2025-02-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_shipment_created_at_and_more'),
    ]

    operations = [
    
    ]
