# Generated by Django 4.2.16 on 2025-02-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_uuid_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(null=True, through='api.CustomerUser', to='api.user'),
        ),
    ]
