# Generated by Django 4.2.16 on 2025-02-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_user_customer_customer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
