# Generated by Django 4.2.16 on 2025-02-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
