# Generated by Django 4.2.16 on 2025-02-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customer_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='s_name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
