# Generated by Django 4.2.16 on 2025-02-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_supplier_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supply_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer')]),
        ),
    ]
