# Generated by Django 4.2.16 on 2025-02-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_supplier_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
