# Generated by Django 4.2.16 on 2025-02-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_supplier_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supply_type',
            new_name='supplier_type',
        ),
    ]
