# Generated by Django 4.2.16 on 2025-02-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_supply_type_supplier_supplier_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='uploads/default.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(null=True, through='api.WarehouseProduct', to='api.warehouse'),
        ),
    ]
