# Generated by Django 4.2.16 on 2025-02-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='buying_price',
            new_name='price',
        ),
    ]
