# Generated by Django 4.2.16 on 2025-02-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(default='a18b1cc5-38ec-4c20-ad36-22c66de0ec8e', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.user'),
        ),
    ]
