# Generated by Django 4.2.16 on 2025-02-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
    ]
