# Generated by Django 4.2.16 on 2025-02-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_supplier_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
