# Generated by Django 4.2.16 on 2025-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='uploads/default.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(null=True, through='api.WarehouseProduct', to='api.warehouse'),
        ),
    ]
