# Generated by Django 4.2.16 on 2025-02-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_product_product_image_product_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
