# Generated by Django 4.2.16 on 2025-02-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
