# Generated by Django 4.2.16 on 2025-02-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('sale_order', 'Sale Order'), ('purchase_order', 'Purchase Order'), ('transfer_order', 'Transfer Order')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
